"""Add bookmodel descrip, price

Revision ID: 2bb572b2a8c6
Revises: 03b9b8082b8f
Create Date: 2024-02-09 19:06:23.507606

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2bb572b2a8c6'
down_revision: Union[str, None] = '03b9b8082b8f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('description', sa.String(), nullable=True))
    op.add_column('books', sa.Column('published_year', sa.Integer(), nullable=True))
    op.add_column('books', sa.Column('price', sa.Integer(), nullable=True))
    op.drop_index('ix_books_isbn', table_name='books')
    op.drop_column('books', 'isbn')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('isbn', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_index('ix_books_isbn', 'books', ['isbn'], unique=True)
    op.drop_column('books', 'price')
    op.drop_column('books', 'published_year')
    op.drop_column('books', 'description')
    # ### end Alembic commands ###
